import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import { ToastContainer, toast } from "react-toastify";
import CreditCard from "../components/creditCardPayment/creditCard";
import InternetBanking from "../components/internetBanking/internetBanking";
import styles from "../styles/Home.module.css";

const customerData = {
  name: "John doe",
  email: "testOmise@mercil.com",
  amount: 100000, //satang unit
};
export default function Home() {
  const [status, setStatus] = useState<any>(null);
  // const { OmiseCard } = window;

  // if (window == undefined) {
  //   const { OmiseCard } = window;
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <CreditCard />
        <InternetBanking />
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>
    </div>
  );
}
